name: DSMRealTime
version: 1.0.1
main: org.projectdsm.dsmrealtime.DSMRealTime
api-version: "1.16"
authors: [HS_Orion]
description: Sets the game time and weather of the spigot server to the time and weather in real life
website: https://projectdsm.org
commands:
 synctime:
   description: Enable, Disable or view status of Sync Time
   usage: /<command> [enable/disable]
 syncweather:
   description: Enable, Disable or view status of Sync Weather
   usage: /<command> [enable/disable]